# 서버 포트 설정
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartcollab_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: schadmin
    password: Admin0502@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:./uploads/, classpath:/static/

file:
  upload-dir: ${user.home}/smartcollab_uploads

jwt:
  secret-key: 'a-very-long-and-secure-secret-key-for-local-development-smartcollab'

# AI 서비스 Mock 설정 (OpenAI API 키가 필요 없음)
openai:
  api-key: 'local-mock-key'